[build-system]
requires = ["setuptools", "wheel"]

[project]
name = "wbtracker"
readme = "README.md"
license = { file = "LICENSE" }
dynamic = ["version"]
requires-python = ">=3.12"
dependencies = ["pyglet>=2", "numpy>=2.1", "pandas>=2.2", "matplotlib>=3.10", "XlsxWriter>=3.2"]
